import pyarrow as pa
import pyarrow.parquet as pq
import random


RRM_PRMOPT="""## You are a helpful assistant in evaluating the quality of the responses for a given user query.
Your goal is to select the best response for the given user query. Select Response A or Response B, that is better for the given user query. The two responses are generated by two different AI assistants respectively. Do NOT say both / neither are good.

## Here are some rules of the evaluation:
(1) If the instruction does not contain harmful content, you should prioritize evaluating whether the output honestly/precisely/closely executes the instruction, then consider its helpfulness, accuracy, level of detail, harmlessness, etc.
(2) If the instruction contains harmful content, prioritize the harmlessness and safety of the response.
(3) Responses should NOT contain more/less than what the instruction asks for, as such responses do NOT precisely execute the instruction.
(4) You should avoid any potential bias and your judgment should be as objective as possible.
    Here are some potential sources of bias:
    - The order in which the responses were presented should NOT affect your judgment, as
    Response A and Response B are equally likely to be the better.
    - The length of the responses should NOT affect your judgement, as a longer response does not necessarily correspond to a better response. When making your decision, evaluate if the response length is appropriate for the given instruction.

## Input Data

### Context
{context}

### Query
{query}

### Response A
{response_1}

### Response B
{response_2}

## Output Format
The final verdict is [[A]] or [[B]]

Please output your analysis and final verdict:
"""

RRM_RUBRIC_PRMOPT="""## You are an objective, impartial, and unbiased content evaluator. Given a user query and two candidate assistant responses, produce a rigorous, evidence-based comparison and a single final verdict indicating which response better fulfills the user’s intent.

### Important constraints (must follow exactly):
1. Work only from the provided, (Assistant A), and (Assistant B). Do not introduce outside facts or assumptions.
2. Output only the structured block described below and nothing else (no preamble, no postscript).
3. Use exactly three evaluation criteria (no more, no fewer). The criteria must be distinct (non-overlapping) and focused on observable differences between the two responses.
4. For each criterion, provide: A short name, A one-sentence explanation of what it measures and why it matters. Each of analyses must explicitly identify the response’s strengths AND weaknesses, especially the concrete defects relevant to that criterion.
5. In each analysis: When pointing out a defect, explain why it is a defect with respect to the criterion (e.g., “fails to answer X”, “contradicts user intent”, “includes factual error”, “provides irrelevant content”). If a response lacks relevant content, clearly state: “Response A/B lacks evidence for X.” Every Judge analysis must include: (a) what works, (b) what fails, (c) concrete evidence, and (d) criterion-based impact.
6. After the three criteria blocks, give a single final verdict line containing exactly [[A]] or [[B]] (choose the response that better meets the query overall).

### Required output format (produce exactly this structure — replace placeholders with real content):
<Criteria 1> Name. Explanation. 
    <Judge A>xxx</Judge A>
    <Judge B>xxx</Judge B>
</Criteria 1>
<Criteria 2> Name. Explanation. 
    <Judge A>xxx</Judge A>
    <Judge B>xxx</Judge B>
</Criteria 2>
<Criteria 3> Name. Explanation. 
    <Judge A>xxx</Judge A>
    <Judge B>xxx</Judge B>
</Criteria 3>
The final verdict is [[A]] or [[B]]

### Input:

[Context]:
{context}

[User Question]:
{query}

[The Start of Assistant A's Answer]:
{response_1}
[The End of Assistant A's Answer]

[The Start of Assistant B's Answer]:
{response_2}
[The End of Assistant B's Answer]

Please output your analysis and final verdict:
"""

def build_criteria_TTS_conversation(idx, query, chosen, rejected, context=""):

    if random.random() > 0.5:
        ground_truth = 1
        prompt = RRM_RUBRIC_PRMOPT.format(query=query, response_1=rejected, response_2=chosen, context=context)
    else:
        ground_truth = 0
        prompt = RRM_RUBRIC_PRMOPT.format(query=query, response_1=chosen, response_2=rejected, context=context)
    
    data = {
        "data_source": "",
        "prompt": [
            {
                "role": "user",
                "content": prompt,
            }
        ],
        'reward_model': {
            'ground_truth': ground_truth,
        },
        "extra_info": {
            "idx":  idx
        }
    }
    
    return data, ground_truth

def build_skywork_lang_data():

    parquet_file = pq.ParquetFile("/workspace/mnt/lxb_work/hf_dir/hf_dataset/Skywork-Reward-Preference-80K-v0.2/data/train-00000-of-00001.parquet")

    lang_train_data = []
    ground_truth_0 = ground_truth_1 = 0
    for batch in parquet_file.iter_batches(batch_size=10000):
        
        df = batch.to_pandas()
        for idx, row in df.iterrows():
            if len(row['rejected']) == 2:
                
                data, ground_truth = build_criteria_TTS_conversation(idx, row['chosen'][0]['content'], row['chosen'][1]['content'], row['rejected'][1]['content'])
                data['data_source'] = "Skywork-Reward-Preference-80K-v0.2"
            else:
                context = ""
                for c in row['rejected'][:-2]:
                    context += c['content']
                
                data, ground_truth = build_criteria_TTS_conversation(idx, row['chosen'][-2]['content'], row['chosen'][-1]['content'], row['rejected'][-1]['content'], context)
            
            data['data_source'] = "Skywork-Reward-Preference-80K-v0.2"
            lang_train_data.append(data)

            if ground_truth == 1:
                ground_truth_1 += 1
            else:
                ground_truth_0 += 1
    
    print(ground_truth_0, ground_truth_1)
    random.shuffle(lang_train_data)
    table = pa.Table.from_pylist(lang_train_data)
    pq.write_table(table, "/workspace/mnt/lxb_work/GRM/Tau-omni/data/rrm_skywork_rubric_train_data.parquet")

def main():

    build_skywork_lang_data()

if __name__ == "__main__":
    main()